services:
    node:
        container_name: events-server
        image: 'node:latest'
        working_dir: /home/node/app
        command:
            - /bin/sh
            - '-c'
            - 'npm install && npm start'
        ports:
            - '5000:5000'
        volumes:
            - './src:/home/node/app'
        links:
            - mongo
    mongo:
        container_name: demo-mongo
        image: 'mongo:latest'
        ports:
            - '27017:27017'