services:
     app:
        container_name: camara-docker-node
        restart: always
        build: .
        ports:
         - '5900:5200'
    
    docker-mongo:
        container_name: demo-mongo
        image: 'mongo:latest'
        ports:
            - '27017:27017'