export const EVENT_LIST_REQUEST = 'EVENT_LIST_REQUEST'
export const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS'
export const EVENT_LIST_FAIL = 'EVENT_LIST_FAIL'

export const EVENT_DETAILS_REQUEST = 'EVENT_DETAILS_REQUEST'
export const EVENT_DETAILS_SUCCESS = 'EVENT_DETAILS_SUCCESS'
export const EVENT_DETAILS_FAIL = 'EVENT_DETAILS_FAIL'

export const EVENT_DESTROY_REQUEST = 'EVENT_DESTROY_REQUEST'
export const EVENT_DESTROY_SUCCESS = 'EVENT_DESTROY_SUCCESS'
export const EVENT_DESTROY_FAIL = 'EVENT_DESTROY_FAIL'

export const EVENT_DELETE_REQUEST = 'EVENT_DELETE_REQUEST'
export const EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS'
export const EVENT_DELETE_FAIL = 'EVENT_DELETE_FAIL'

export const EVENT_IMPORT_REQUEST = 'EVENT_IMPORT_REQUEST'
export const EVENT_IMPORT_SUCCESS = 'EVENT_IMPORT_SUCCESS'
export const EVENT_IMPORT_FAIL = 'EVENT_IMPORT_FAIL'
export const EVENT_IMPORT_RESET = 'EVENT_IMPORT_RESET'


export const UPLOAD_CSV_REQUEST = 'UPLOAD_CSV_REQUEST'
export const UPLOAD_CSV_SUCCESS = 'UPLOAD_CSV_SUCCESS'
export const UPLOAD_CSV_FAIL = 'UPLOAD_CSV_FAIL'
export const UPLOAD_CSV_RESET = 'UPLOAD_CSV_RESET'